# **Students Performance Analysis**

In [ ]:
import numpy as np

marks = np.array([[67,76,86,68],                  ## rows = Students , column = Subjects
                   [88,56,87,55],
                   [78,88,66,51],
                   [45,76,71,61],
                   [56,66,77,88]])
attendance = np.array([74,77,73,72,78])           ## attendance of 5 students.
bonus = np.array([5,4,3,4])
# Print marks of 3rd Students.
print("-----------indexing and slicing-------------")
print(f"Marks of 3rd Students : {marks[2,:]}")
# print marks of 2nd subject of all students.
print(f"Marks of 2nd Subject of all Students are : {marks[:,1]}")
# print marks of last two students.
print(f"Marks of last two students are : \n{marks[3:,:]}")
# print marks of first 2 student of first 3 subjects.
print(f"Marks of first 2 students of first 3 subjects are : \n{marks[:2,:3]}")
print("-----------------------------reshape------------------------------\n")
re_sh = marks.reshape(20)
print(f"Before using reshape() : \n{marks} \nAfter using reshape() : {re_sh}\n")
print("-----------------------------resize----------------------------------")
re_si = np.resize(re_sh,(4,5))
print(f"Before using resize() : {re_sh} \nAfter using resize() : \n{re_si}")

print("----------------------------Stacking-----------------------------")

stk = np.vstack([marks,bonus])
print(stk)
print("----------------------------Splitting---------------------------")
print("--------------------------Row Splitting-------------------------")
row_split = np.array_split(stk,2)
print(row_split)

print("--------------    -------column Spliting------------------------")
col_split = np.array_split(marks,2,axis = 1)
print(col_split)

print("--------------------------Broadcasting--------------------------")
adjusted_marks = marks + bonus
print(f"Add bonus to all Subjects : \n {adjusted_marks}")

# Increase marks of students with attendance > 75% by 5 marks using broadcasting + condition.
final_marks = np.where(attendance[:,None] > 75,adjusted_marks + 5,adjusted_marks)
print(f"\n Final Marks : \n {final_marks}")


print("-------------------------------------------------------------------------")
avg_marks = final_marks.mean(axis = 1)
print(avg_marks)

top_student = np.argmax(avg_marks)
print("Index of topper : ",top_student)


-----------indexing and slicing-------------
Marks of 3rd Students : [78 88 66 51]
Marks of 2nd Subject of all Students are : [76 56 88 76 66]
Marks of last two students are : 
[[45 76 71 61]
 [56 66 77 88]]
Marks of first 2 students of first 3 subjects are : 
[[67 76 86]
 [88 56 87]]
-----------------------------reshape------------------------------

Before using reshape() : 
[[67 76 86 68]
 [88 56 87 55]
 [78 88 66 51]
 [45 76 71 61]
 [56 66 77 88]] 
After using reshape() : [67 76 86 68 88 56 87 55 78 88 66 51 45 76 71 61 56 66 77 88]

-----------------------------resize----------------------------------
Before using resize() : [67 76 86 68 88 56 87 55 78 88 66 51 45 76 71 61 56 66 77 88] 
After using resize() : 
[[67 76 86 68 88]
 [56 87 55 78 88]
 [66 51 45 76 71]
 [61 56 66 77 88]]
----------------------------Stacking-----------------------------
[[67 76 86 68]
 [88 56 87 55]
 [78 88 66 51]
 [45 76 71 61]
 [56 66 77 88]
 [ 5  4  3  4]]
----------------------------Splitting--------